name: Push to GH Pages
on: [push, workflow_dispatch]
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
        ref: 'master'
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_KEY }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
    - run: |
        git remote add bitbucket git@github.com:corsframe/corsframe.github.io.git
        git config --global user.email "<>"
        git config --global user.name "GH Pages Bot"
        git checkout master
        git push -u bitbucket master